language: rust
cache: cargo
matrix:
  include:
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin

script:
  - cargo build --target "$TARGET" --verbose
  - cargo test --target "$TARGET" --verbose

before_deploy:
  - cargo test --target "$TARGET" --release
  - git config --local user.name "Gabriel Barker"
  - git config --local user.email "$GITHUB_EMAIL"
  - name="clyp-test-release"
  - git tag 'v0.0.0'
  - mkdir $name
  - cp target/$TARGET/release/clyp $name/
  - cp README.md LICENSE $name/
  - tar czvf $name.tar.gz $name

deploy:
  provider: releases
  api_key: *GITHUB_TOKEN
  file: clyp-test-release.tar.gz
  skip_cleanup: true
  draft: true
  on:
    branch: main
